### PR TITLE
Fix schema names

### PR DESCRIPTION
**Pull request by dgreenslade**
Changes to match hardcoded attribute names used by Map Chef

### CODE REVIEW

**Review by geojayuu — COMMENTED** [review]
Where testing this branch an error appears in Airflow (and the dags are unavailable to run):
Broken DAG: [/home/airflow/gcs/dags/dags.py] 'NAME_EN'

Think this is related to some country config files not having NAME_EN within them. For example compare the yemen.yaml file with haiti.yaml (the latter is missing a number of HXD keys) ie:
adm0:
  cod:
    column_names:
      NAME_EN: admin0Name_en
      PCODE: pcode
adm1:
  cod:
    column_names:
      NAME_EN: admin1Name_en
      PCODE: pcode
      par_pcode: par_pcode

Think the NAME_EN value and relevant PCODE values will need adding to all remaining country YAML files as well.

**Comment by dgreenslade** [comment]
Hi @geojayuu , I think I've resolved the schema names issue with NAME_EN causing an issue.

**Review by geojayuu — COMMENTED** [review]
I'm still seeing errors in AirFlow:
Broken DAG: [/home/airflow/gcs/dags/dags.py] 'ADM1_EN'

**Comment by geojayuu** [comment]
Tested latest changes without error.

**Pull request merged**
